//
//  MainModels.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
  
  struct Request: Codable {
    var page, size: Int?
    var q: String?
    var sort: [String]?
  }
  
  struct DepartmentResponse: Codable {
    var content: [Department]
    var pageable: Pageable
    var last, first, empty: Bool
    var totalPages, totalElements, numberOfElements, size, number: Int
    var sort: Sort
  }
  
  struct Department: Codable {
    var id: Int
    var name, groupName, since, inTime, outTime, created, modified: String
  }
  
  struct Pageable: Codable {
    var sort: Sort
    var pageSize, pageNumber, offset: Int
    var unpaged, paged: Bool
  }
  
  struct Sort: Codable {
    var unsorted, sorted, empty: Bool
  }
}
