//
//  MainWorker.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Moya

class MainWorker
{
  func doDepartmentList(request: Main.Request) -> Single<Main.DepartmentResponse> {
    return Provider.rx.request(.Department(params: request)).map { moyaResponse -> Main.DepartmentResponse in
      if moyaResponse.statusCode == 200 {
        let response = try! JSONDecoder().decode(Main.DepartmentResponse.self, from: moyaResponse.data)
        return response
      }
      throw AppError.serverError
    }
  }
  
  func doDeleteDepartment(id: String) -> Completable {
    return Provider.rx.request(.DeleteDepartment(id: id)).map { (moyaResponse) -> Int in
      if moyaResponse.statusCode == 200 {
        return 1
      }
      throw AppError.serverError
    }.asCompletable()
  }
}
