//
//  MainPresenter.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
  func presentDepartments(departmentResponse: Main.DepartmentResponse)
  func presentSuccessDelete()
}

class MainPresenter: MainPresentationLogic
{
  weak var viewController: MainDisplayLogic?
  func presentDepartments(departmentResponse: Main.DepartmentResponse) {
    viewController?.displayDepartment(departmentResponse: departmentResponse)
  }
  
  func presentSuccessDelete() {
    viewController?.displaySuccessDelete()
  }
}
