//
//  CreateDepartmentWorker.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Moya

class CreateDepartmentWorker
{
  func doSaveDepartment(request: CreateDepartment.Request) -> Single<Main.Department> {
    return Provider.rx.request(.CreateDepartment(params: request)).map { (moyaResponse) -> Main.Department in
      if moyaResponse.statusCode == 200 {
        let response = try! JSONDecoder().decode(Main.Department.self, from: moyaResponse.data)
        return response
      }
      throw AppError.serverError
    }
  }
  
  func doUpdateDepartment(id: String, request: CreateDepartment.Request) -> Single<Main.Department> {
    return Provider.rx.request(.UpdateDepartment(id: id, params: request)).map { (moyaResponse) -> Main.Department in
      if moyaResponse.statusCode == 200 {
        let response = try! JSONDecoder().decode(Main.Department.self, from: moyaResponse.data)
        return response
      }
      throw AppError.serverError
    }
  }
}
