//
//  CreateDepartmentModels.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateDepartment
{
  struct Request: Codable {
    var groupName, inTime, name, outTime, since : String
  }
  
  enum DateSelection {
    case Intime
    case Outtime
    case Since
  }
}
