//
//  CreateDepartmentRouter.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateDepartmentRoutingLogic
{
  
}

protocol CreateDepartmentDataPassing
{
  var dataStore: CreateDepartmentDataStore? { get }
}

class CreateDepartmentRouter: NSObject, CreateDepartmentRoutingLogic, CreateDepartmentDataPassing
{
  weak var viewController: CreateDepartmentViewController?
  var dataStore: CreateDepartmentDataStore?
  
  // MARK: Routing

  // MARK: Navigation
  
  // MARK: Passing data
  
}
