//
//  CreateDepartmentPresenter.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateDepartmentPresentationLogic
{
  func presentSuccessCreate(department: Main.Department)
  func presentSuccessUpdate(department: Main.Department)
  func presentSuccessDrafted(department: Department)
  func presentSuccessUpdateDraft(department: Department)
  func presentFailed(message: String)
}

class CreateDepartmentPresenter: CreateDepartmentPresentationLogic
{
  weak var viewController: CreateDepartmentDisplayLogic?
  
  func presentSuccessCreate(department: Main.Department) {
    viewController?.displaySuccessCreate(department: department)
  }
  
  func presentSuccessUpdate(department: Main.Department) {
    viewController?.displaySuccessUpdate(department: department)
  }
  
  func presentSuccessDrafted(department: Department) {
    viewController?.displaySuccessDrafted(department: department)
  }
  
  func presentSuccessUpdateDraft(department: Department) {
    viewController?.displaySuccessUpdateDraft(department: department)
  }
  
  func presentFailed(message: String) {
    viewController?.displayFailed(message: message)
  }
}
