//
//  ProjectListRouter.swift
//  sampleCRUD
//
//  Created by syndromme on 24/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProjectListRoutingLogic
{
  func routeToCreateProject()
  func routeToDraftListScene()
  func routeToSorttListScene()
}

protocol ProjectListDataPassing
{
  var dataStore: ProjectListDataStore? { get }
}

class ProjectListRouter: NSObject, ProjectListRoutingLogic, ProjectListDataPassing
{
  weak var viewController: ProjectListViewController?
  var dataStore: ProjectListDataStore?
  
  // MARK: Routing
  func routeToCreateProject() {
    let destinationVC = CreateProjectViewController(nibName: "CreateProjectView", bundle: nil)
    var destinationDS = destinationVC.router!.dataStore!
    passDataToCreateProject(source: dataStore!, destination: &destinationDS)
    navigateToCreateProject(source: viewController!, destination: destinationVC)
  }
  
  func routeToDraftListScene() {
    let destinationVC = DraftListViewController(nibName: "DraftListView", bundle: nil)
    var destinationDS = destinationVC.router!.dataStore!
    passDataToDraftList(source: dataStore!, destination: &destinationDS)
    navigateToDraftList(source: viewController!, destination: destinationVC)
  }
  
  func routeToSorttListScene() {
    let destinationVC = SortListVC(nibName: "SortListView", bundle: nil)
    destinationVC.doneTapped = {(sender) in
      self.dataStore?.sorts = sender
      self.viewController?.projects.removeAll()
      self.viewController?.interactor?.getProjectList(page: 0, name: "", size: Constant.paginateSize)
    }
    destinationVC.selectedSort = dataStore?.sorts ?? []
    destinationVC.sortType = .Project
    navigateToSortProject(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  func navigateToCreateProject(source: ProjectListViewController, destination: CreateProjectViewController)
  {
    source.navigationController?.pushViewController(destination, animated: true)
  }
  
  func navigateToDraftList(source: ProjectListViewController, destination: DraftListViewController)
  {
    source.navigationController?.pushViewController(destination, animated: true)
  }
  
  func navigateToSortProject(source: ProjectListViewController, destination: SortListVC)
  {
    let nav = UINavigationController(rootViewController: destination)
    nav.modalTransitionStyle = .crossDissolve
    nav.modalPresentationStyle = .overFullScreen
    source.present(nav, animated: true, completion: nil)
  }

  // MARK: Passing data
  func passDataToCreateProject(source: ProjectListDataStore, destination: inout CreateProjectDataStore)
  {
    destination.selectedProject = source.selectedProject
//    destination.draftProject = 
  }
  
  func passDataToDraftList(source: ProjectListDataStore, destination: inout DraftListDataStore)
  {
    destination.draftType = .Project
  }
}
