//
//  ProjectListWorker.swift
//  sampleCRUD
//
//  Created by syndromme on 24/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Moya

class ProjectListWorker
{
  func doProjectList(request: ProjectList.Request) -> Single<ProjectList.ProjectResponse> {
    return Provider.rx.request(.Project(params: request)).map { moyaResponse -> ProjectList.ProjectResponse in
      if moyaResponse.statusCode == 200 {
        let response = try! JSONDecoder().decode(ProjectList.ProjectResponse.self, from: moyaResponse.data)
        return response
      }
      throw AppError.serverError
    }
  }
  
  func doDeleteProject(id: String) -> Completable {
    return Provider.rx.request(.DeleteProject(id: id)).map { (moyaResponse) -> Int in
      if moyaResponse.statusCode == 200 {
        return 1
      }
      throw AppError.serverError
    }.asCompletable()
  }
}
