//
//  ProjectListModels.swift
//  sampleCRUD
//
//  Created by syndromme on 24/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProjectList
{
  struct Request: Codable {
    var page, size: Int?
    var name, amount: String?
    var sort: [String]?
  }
  
  struct ProjectResponse: Codable {
    var content: [Project]
    var pageable: Main.Pageable
    var last, first, empty: Bool
    var totalPages, totalElements, numberOfElements, size, number: Int
    var sort: Main.Sort
  }
  
  struct Project: Codable {
    var id, amount: Int
    var name, created, modified: String
    var startDate, endDate: String?
  }
}
