//
//  CreateProjectRouter.swift
//  sampleCRUD
//
//  Created by syndromme on 24/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateProjectRoutingLogic
{
  
}

protocol CreateProjectDataPassing
{
  var dataStore: CreateProjectDataStore? { get }
}

class CreateProjectRouter: NSObject, CreateProjectRoutingLogic, CreateProjectDataPassing
{
  weak var viewController: CreateProjectViewController?
  var dataStore: CreateProjectDataStore?
  
  // MARK: Routing
  

  // MARK: Navigation
  
  
  // MARK: Passing data
  
}
