//
//  CreateProjectWorker.swift
//  sampleCRUD
//
//  Created by syndromme on 24/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Moya

class CreateProjectWorker
{
  func doSaveProject(request: CreateProject.Request) -> Single<ProjectList.Project> {
    return Provider.rx.request(.CreateProject(params: request)).map { (moyaResponse) -> ProjectList.Project in
      if moyaResponse.statusCode == 200 {
        let response = try! JSONDecoder().decode(ProjectList.Project.self, from: moyaResponse.data)
        return response
      }
      throw AppError.serverError
    }
  }
  
  func doUpdateProject(id: String, request: CreateProject.Request) -> Single<ProjectList.Project> {
    return Provider.rx.request(.UpdateProject(id: id, params: request)).map { (moyaResponse) -> ProjectList.Project in
      if moyaResponse.statusCode == 200 {
        let response = try! JSONDecoder().decode(ProjectList.Project.self, from: moyaResponse.data)
        return response
      }
      throw AppError.serverError
    }
  }
}
