//
//  CreateProjectModels.swift
//  sampleCRUD
//
//  Created by syndromme on 24/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateProject
{
  struct Request: Codable {
    var amount: Int
    var name, startDate, endDate : String
  }
  
  enum DateSelection {
    case StartDate
    case EndDate
  }
}
