//
//  AuthWorker.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Moya
import KeychainAccess

class AuthWorker
{
  func doLogin(request: Auth.Request) -> Single<Auth.Response> {
    return Provider.rx.request(.Auth(params: request)).map { moyaResponse -> Auth.Response in
        if moyaResponse.statusCode == 200 {
          let response = try! JSONDecoder().decode(Auth.Response.self, from: moyaResponse.data)
          try! Keychain().set(response.access_token, key: "AccessToken")
          try! Keychain().set(response.refresh_token, key: "RefreshToken")
          try! Keychain().set(response.token_type, key: "TokenType")
          return response
        }
        throw AppError.serverError
      }
  }
}
