//
//  AuthRouter.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AuthRoutingLogic
{
  func routeToMainScene()
  func routeToMenuScene()
}

protocol AuthDataPassing
{
  var dataStore: AuthDataStore? { get }
}

class AuthRouter: NSObject, AuthRoutingLogic, AuthDataPassing
{
  weak var viewController: AuthViewController?
  var dataStore: AuthDataStore?
  
  // MARK: Routing
  func routeToMainScene() {
    let destinationVC = MainViewController(nibName: "MainView", bundle: nil)
    var destinationDS = destinationVC.router!.dataStore!
    passDataToMain(source: dataStore!, destination: &destinationDS)
    navigateToMain(source: viewController!, destination: destinationVC)
  }
  
  func routeToMenuScene() {
    let destinationVC = MenuVC(nibName: "MenuView", bundle: nil)
    navigateToMenu(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  func navigateToMain(source: AuthViewController, destination: MainViewController)
  {
    let nav = UINavigationController(rootViewController: destination)
    nav.modalTransitionStyle = .crossDissolve
    nav.modalPresentationStyle = .overFullScreen
    source.present(nav, animated: true, completion: nil)
  }
  
  func navigateToMenu(source: AuthViewController, destination: MenuVC)
  {
    let nav = UINavigationController(rootViewController: destination)
    nav.modalTransitionStyle = .crossDissolve
    nav.modalPresentationStyle = .overFullScreen
    source.present(nav, animated: true, completion: nil)
  }
  
  // MARK: Passing data
  func passDataToMain(source: AuthDataStore, destination: inout MainDataStore)
  {
    
  }
  
}
