//
//  AuthModels.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Auth
{
  struct Request: Codable {
    var grant_type, scope, username, password: String
  }
  
  struct Response: Codable {
    var access_token, token_type, refresh_token, scope, jti: String
    var expires_in: Int
  }
}
