//
//  DraftListModels.swift
//  sampleCRUD
//
//  Created by syndromme on 22/10/20.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

enum DraftList
{
  enum DraftType {
    case Department
    case Project
  }
}

class Department: Object {
  @objc dynamic var name, groupName, since, inTime, outTime: String?
  
    required override init() {
    super.init()
  }
  
  required init(name: String?, groupName: String?, since: String?, inTime: String?, outTime: String?) {
    super.init()
    self.name = name
    self.groupName = groupName
    self.since = since
    self.inTime = inTime
    self.outTime = outTime
  }
}

class Project: Object {
  @objc dynamic var name, amount, startDate, endDate: String?
  
    required override init() {
    super.init()
  }
  
  required init(name: String?, amount: String?, startDate: String?, endDate: String?) {
    super.init()
    self.name = name
    self.amount = amount
    self.startDate = startDate
    self.endDate = endDate
  }
}
